### ISSUE TITLE
Is it possible to run the application without AllowSynchronousIO 

### ISSUE THREAD

**Issue by abhijithmjayan** [Moesif/moesif-netcore-example#23]
1. Is it possible torun the application without following in .net core 3.1
                    .ConfigureKestrel((context, options) => {
                        options.AllowSynchronousIO = true;
                    });

2. How can I collect the database calls with Moesif?

**Comment by dgilling** [comment]
1. At the moment, looks like AllowSynchronousIO due to [changes in .NET Core 3.x.](https://khalidabuhakmeh.com/dotnet-core-3-dot-0-allowsynchronousio-workaround) Does this impact your app? We do have plans to update the SDK to support ReadAsync(), etc but currently it does not use these new constructs. 

2. Moesif can optimistically log requests to a database if it's to a 3rd party HTTP API such as DynamoDb, but it's not guaranteed to work for all scenarios. Communication such as to a local database like SQLite is not logged. Ensure [Capture_Outgoing_Requests](https://www.moesif.com/docs/server-integration/dotnet/#capture_outgoing_requests) is enabled.

```csharp
{
    {"ApplicationId": "Your Moesif Application Id"},
    {"Capture_Outgoing_Requests", true}
  }
```

**Comment by abhijithmjayan** [comment]
I'm using SQL Server and enabled Capture_Outgoing_Requests. But its not working.

**Comment by dgilling** [comment]
I see. At the moment it's not supported. Feel free to send me us an email to support@moesif.com describing your application and use case and we can see how to best help.

**Comment by dgilling** [comment]
@abhijithmjayan to close the loop on this, version 1.3.11 of the SDK supports async body methods without requiring `options.AllowSynchronousIO = true;`. Due to a limitation, the response.body will not be logged. If this is required, you will still need `options.AllowSynchronousIO = true;`
